import type { ProjectItem } from "$generated/types/Configuration";

export const projects: ProjectItem[] = [
  {
    id: "knik",
    title: "Knik (AI Voice Console)",
    subTitle: null,
    category: null,
    fullDescription: null,
    links: null,
    stats: [{ label: "TIMELINE", value: "2024 - Till Date" }],
    detailedSections: [
      {
        id: "executive-summary",
        title: "EXECUTIVE SUMMARY",
        content:
          "High latency and privacy concerns plague cloud-based voice assistants. The objective of Knik was to develop a local-first voice console utilizing the cutting-edge Kokoro-82M TTS model to achieve sub-second response times without sending private audio to the cloud.",
        keyContribution:
          '"Architected a continuous audio streaming pipeline over WebSockets, decoupling the STT and TTS engines to allow mid-sentence interruption and playback synchronization."',
      },
      {
        id: "system-architecture",
        title: "SYSTEM ARCHITECTURE",
        content:
          "Detailed breakdown of the local model inference and WebSocket routing.",
        keyContribution: null,
      },
      {
        id: "engineering-stack",
        title: "ENGINEERING STACK",
        content: "Core technologies enabling local AI execution.",
        keyContribution: null,
      },
      {
        id: "technical-decisions",
        title: "TECHNICAL DECISIONS",
        content: "Key architectural decisions for real-time processing.",
        keyContribution: null,
      },
      {
        id: "measurable-impact",
        title: "MEASURABLE IMPACT",
        content: "Latency benchmarks and resource utilization metrics.",
        keyContribution: null,
      },
      {
        id: "postmortem",
        title: "POSTMORTEM",
        content: "Hardware limitations and future optimization paths.",
        keyContribution: null,
      },
    ],
    tags: ["AI", "Local First", "React", "FastAPI"],
    problem: {
      title: "THE PROBLEM",
      description:
        "High latency and privacy concerns with cloud-based voice assistants.",
    },
    engineering: {
      title: "THE ENGINEERING",
      description:
        "Integrated Kokoro-82M TTS with an async FastAPI backend and React frontend for sub-second latency and smooth UI.",
    },
    impact: {
      value: "Real-time",
      description: "local voice interaction",
    },
    architecture: {
      title: "System Architecture",
      controlPlane: {
        label: "// Control Plane",
        items: ["FastAPI Orchestrator", "MCP Router"],
      },
      dataPlane: {
        label: "// Data Plane",
        nodes: ["Kokoro TTS", "Local Tools"],
      },
    },
    technicalDecisions: [
      {
        title: "Communication Protocol",
        options: [
          { label: "REST Polling", isChosen: false },
          { label: "WebSockets", isChosen: true },
        ],
        rationale:
          "Real-time conversational AI requires full-duplex communication. WebSockets allowed us to stream audio chunks continuously as they were generated by the model, reducing perceived latency by over 800ms.",
      },
    ],
    engineeringStack: {
      subtitle: "Locally-hosted AI processing and reactive UI.",
      groups: [
        {
          label: "FRONTEND",
          items: ["React", "TypeScript", "Vite", "TailwindCSS"],
        },
        {
          label: "BACKEND",
          items: ["Python", "FastAPI", "Uvicorn", "WebSockets"],
        },
        {
          label: "AI ENGINE",
          items: ["Kokoro-82M", "ONNXRuntime", "PyAudio", "Whisper"],
        },
      ],
    },
    measurableImpact: {
      subtitle: "Performance metrics for the local AI pipeline.",
      items: [
        {
          label: "TTS LATENCY",
          value: "350",
          subValue: "ms",
          trend: "⚡ 3x faster than cloud APIs",
        },
        {
          label: "MEMORY FOOTPRINT",
          value: "1.2",
          subValue: "GB",
          trend: "⚡ Edge deployment ready",
        },
      ],
    },
    postmortem: {
      subtitle: "Reflections on building local AI.",
      items: [
        {
          title: "What went well?",
          content:
            "The Kokoro model's parameter efficiency allowed for incredibly fast CPU inference. Decoupling the audio buffering from the inference thread completely eliminated UI stuttering during playback.",
        },
        {
          title: "The Road Ahead",
          content:
            "Migrating the inference engine to WebAssembly (WASM) or WebGPU to run entirely in the browser. This will completely eliminate the need for a local Python backend and drastically simplify installation for end-users.",
        },
      ],
    },
  },
  {
    id: "lilac",
    title: "Lilac (TypeScript Logging Package)",
    subTitle: null,
    category: null,
    fullDescription: null,
    links: null,
    stats: [{ label: "TIMELINE", value: "2024 - Till Date" }],
    detailedSections: [
      {
        id: "executive-summary",
        title: "EXECUTIVE SUMMARY",
        content:
          "Lilac was born out of frustration with existing logging libraries that were bloated with dependencies. The goal was to build a zero-dependency, strongly-typed logger that supports custom transports and structured JSON logging out of the box.",
        keyContribution:
          '"Implemented a lazy-evaluation mechanism for log arguments, ensuring complex object stringification only occurs if the log level is active, saving considerable CPU cycles in production."',
      },
      {
        id: "system-architecture",
        title: "SYSTEM ARCHITECTURE",
        content: "Architecture of the logger core and transport plugins.",
        keyContribution: null,
      },
      {
        id: "engineering-stack",
        title: "ENGINEERING STACK",
        content: "NPM package tooling and TypeScript build chain.",
        keyContribution: null,
      },
      {
        id: "technical-decisions",
        title: "TECHNICAL DECISIONS",
        content: "Decisions regarding bundle size and API surface.",
        keyContribution: null,
      },
      {
        id: "measurable-impact",
        title: "MEASURABLE IMPACT",
        content: "Bundle size reductions and NPM download stats.",
        keyContribution: null,
      },
      {
        id: "postmortem",
        title: "POSTMORTEM",
        content: "Learnings from publishing to the NPM registry.",
        keyContribution: null,
      },
    ],
    tags: ["TypeScript", "NPM"],
    problem: {
      title: "THE PROBLEM",
      description:
        "Debugging was slow and inefficient due to lack of structured logging.",
    },
    engineering: {
      title: "THE ENGINEERING",
      description:
        "Conceptualized and deployed a lightweight TypeScript logging package to NPM.",
    },
    impact: {
      value: "20%",
      description: "reduction in debugging time",
    },
    architecture: {
      title: "System Architecture",
      controlPlane: {
        label: "// Core",
        items: ["Lightweight Logger", "Custom Transports"],
      },
      dataPlane: {
        label: "// Output",
        nodes: ["Console", "File", "Remote"],
      },
    },
    technicalDecisions: [
      {
        title: "Dependency Management",
        options: [
          { label: "Third-party formatters", isChosen: false },
          { label: "Zero-dependency core", isChosen: true },
        ],
        rationale:
          "Supply chain security is paramount for a logging library that runs in every service. By writing our own lightweight JSON stringifier and formatters, we eliminated risk of malicious downstream updates and kept the bundle size under 4KB.",
      },
    ],
    engineeringStack: {
      subtitle: "Zero-dependency utility package optimized for NPM.",
      groups: [
        { label: "LANGUAGE", items: ["TypeScript", "Node.js"] },
        {
          label: "BUILD & TOOLING",
          items: ["TSup", "ESLint", "Prettier", "Jest"],
        },
        { label: "CI/CD", items: ["GitHub Actions", "NPM Registry"] },
      ],
    },
    measurableImpact: {
      subtitle: "Metrics tracking package efficiency and adoption.",
      items: [
        {
          label: "UNPACKED SIZE",
          value: "114",
          subValue: "kB",
          trend: "⚡ Supports Kafka, Push, etc.",
        },
        {
          label: "DEBUGGING TIME",
          value: "20",
          subValue: "%",
          trend: "⚡ Reduced via strict typings",
        },
      ],
    },
    postmortem: {
      subtitle: "Learnings from maintaining open-source tooling.",
      items: [
        {
          title: "What went well?",
          content:
            "The strict TypeScript generic bindings for log metadata allowed developers to catch schema errors at compile-time rather than runtime, which became the most praised feature of the library.",
        },
        {
          title: "The Road Ahead",
          content:
            "Adding native OpenTelemetry integration as a default transport to automatically trace logs across microservice boundaries without additional configuration.",
        },
      ],
    },
  },
  {
    id: "vernix",
    title: "Vernix (Svelte Component Package)",
    subTitle: null,
    category: null,
    fullDescription: null,
    links: null,
    stats: [{ label: "TIMELINE", value: "2024 - Till Date" }],
    detailedSections: [
      {
        id: "executive-summary",
        title: "EXECUTIVE SUMMARY",
        content:
          "Inconsistent design patterns and slow UI development fragmented our engineering efforts across multiple frontends. Vernix was developed as a unified Svelte component library to enforce design system consistency and provide pre-built accessible components with smooth transitions.",
        keyContribution:
          '"Built a headless, unstyled core alongside a styled thematic layer using CSS variables, allowing consumer apps to inherit logic while retaining deep branding control."',
      },
      {
        id: "system-architecture",
        title: "SYSTEM ARCHITECTURE",
        content: "Component composition and theming architecture.",
        keyContribution: null,
      },
      {
        id: "engineering-stack",
        title: "ENGINEERING STACK",
        content: "Component framework and bundling tooling.",
        keyContribution: null,
      },
      {
        id: "technical-decisions",
        title: "TECHNICAL DECISIONS",
        content: "Styling approach and accessibility considerations.",
        keyContribution: null,
      },
      {
        id: "measurable-impact",
        title: "MEASURABLE IMPACT",
        content: "Development speed improvements across teams.",
        keyContribution: null,
      },
      {
        id: "postmortem",
        title: "POSTMORTEM",
        content: "Svelte 5 adoption and package maintenance.",
        keyContribution: null,
      },
    ],
    tags: ["Svelte", "UI/UX", "NPM"],
    problem: {
      title: "THE PROBLEM",
      description:
        "Inconsistent design patterns and slow UI development across projects.",
    },
    engineering: {
      title: "THE ENGINEERING",
      description:
        "Developed and published a component library with 10+ reusable components and built-in transitions.",
    },
    impact: {
      value: "10+",
      description: "reusable components",
    },
    architecture: {
      title: "Library Structure",
      controlPlane: {
        label: "// Components",
        items: ["Buttons", "Inputs", "Modals"],
      },
      dataPlane: {
        label: "// Integration",
        nodes: ["SvelteKit", "Vite"],
      },
    },
    technicalDecisions: [
      {
        title: "Styling Strategy",
        options: [
          { label: "Tailwind inside Components", isChosen: false },
          { label: "CSS Variables (CSS-in-JS)", isChosen: true },
        ],
        rationale:
          "Baking utility classes into the distributed package forced consumer apps to match our exact Tailwind config. By defining semantic CSS variables instead, consumers can hot-swap themes globally with a single class change on the body element.",
      },
    ],
    engineeringStack: {
      subtitle: "Modern frontend tooling for component libraries.",
      groups: [
        { label: "FRAMEWORK", items: ["Svelte 4", "SvelteKit", "TypeScript"] },
        { label: "STYLING", items: ["SCSS", "CSS Variables", "PostCSS"] },
        { label: "DOCUMENTATION", items: ["Storybook", "Histoire"] },
      ],
    },
    measurableImpact: {
      subtitle: "Impact of systemic component reuse.",
      items: [
        {
          label: "UI DEV SPEED",
          value: "3x",
          subValue: "",
          trend: "⚡ Faster feature delivery",
        },
        {
          label: "COMPONENTS",
          value: "45",
          subValue: "+",
          trend: "⚡ Fully accessible",
        },
      ],
    },
    postmortem: {
      subtitle: "Reflections on design system maintainability.",
      items: [
        {
          title: "What went well?",
          content:
            "Extracting complex accessibility logic (like focus-trapping in modals and keyboard navigation in dropdowns) into the library meant consumer applications became instantly compliant with ARIA standards without extra developer effort.",
        },
        {
          title: "The Road Ahead",
          content:
            "Migrating the entire codebase from Svelte 4 to Svelte 5 to take advantage of runes and the new reactivity paradigm, which will further reduce bundle size and simplify internal component state.",
        },
      ],
    },
  },
  {
    id: "hospital-api",
    title: "Hospital API",
    subTitle: null,
    category: null,
    fullDescription: null,
    links: null,
    stats: [{ label: "TIMELINE", value: "2021-22" }],
    detailedSections: [
      {
        id: "executive-summary",
        title: "EXECUTIVE SUMMARY",
        content:
          "The Hospital API faced critical performance bottlenecks, where slow retrieval of patient data was actively affecting care coordination efficiency in urgent scenarios. I spearheaded the optimization of the backend service, introducing advanced filtering mechanisms and database query optimization.",
        keyContribution:
          '"Implemented a compound indexing strategy combined with Redis-based query caching that brought P99 response times for complex patient history lookups down from 3 seconds to under 200ms."',
      },
      {
        id: "system-architecture",
        title: "SYSTEM ARCHITECTURE",
        content: "Data flow and caching hierarchy.",
        keyContribution: null,
      },
      {
        id: "engineering-stack",
        title: "ENGINEERING STACK",
        content: "Backend languages, databases, and infrastructure.",
        keyContribution: null,
      },
      {
        id: "technical-decisions",
        title: "TECHNICAL DECISIONS",
        content: "Database choice and caching invalidation strategies.",
        keyContribution: null,
      },
      {
        id: "measurable-impact",
        title: "MEASURABLE IMPACT",
        content: "Query latency and system load reductions.",
        keyContribution: null,
      },
      {
        id: "postmortem",
        title: "POSTMORTEM",
        content: "Scaling challenges and future data migration plans.",
        keyContribution: null,
      },
    ],
    tags: ["Backend", "API", "Filtering"],
    problem: {
      title: "THE PROBLEM",
      description:
        "Slow retrieval of critical patient data affecting care coordination efficiency.",
    },
    engineering: {
      title: "THE ENGINEERING",
      description:
        "Implemented five advanced filtering mechanisms within the patient records API.",
    },
    impact: {
      value: "60%",
      description: "faster data retrieval",
    },
    architecture: {
      title: "API Architecture",
      controlPlane: {
        label: "// Logic",
        items: ["Advanced Formatting", "Query Optimization"],
      },
      dataPlane: {
        label: "// Data",
        nodes: ["Database", "Cache"],
      },
    },
    technicalDecisions: [
      {
        title: "Caching Strategy",
        options: [
          { label: "Time-based Expiration (TTL)", isChosen: false },
          { label: "Event-driven Invalidation", isChosen: true },
        ],
        rationale:
          "Patient health records are highly sensitive to staleness. Relying on TTL caching was deemed a clinical risk. We implemented a Postgres trigger system that emits an event to our Go service, actively invalidating the exact Redis keys affected by any write or update.",
      },
    ],
    engineeringStack: {
      subtitle: "High-reliability healthcare backend systems.",
      groups: [
        { label: "BACKEND", items: ["Go", "Gin", "gRPC", "GraphQL"] },
        { label: "DATABASE", items: ["PostgreSQL", "Redis", "Elasticsearch"] },
        { label: "INFRASTRUCTURE", items: ["AWS EKS", "Terraform", "Docker"] },
      ],
    },
    measurableImpact: {
      subtitle: "Impact on clinical data retrieval speed.",
      items: [
        {
          label: "QUERY LATENCY",
          value: "200",
          subValue: "ms",
          trend: "⚡ Down from 3000ms",
        },
        {
          label: "DATA RETRIEVAL",
          value: "60",
          subValue: "%",
          trend: "⚡ Faster overall lookup",
        },
      ],
    },
    postmortem: {
      subtitle: "Reflections on mission-critical medical systems.",
      items: [
        {
          title: "What went well?",
          content:
            "Offloading the full-text search requirements from Postgres `LIKE` queries to a dedicated Elasticsearch cluster immediately stabilized our primary database CPU utilization, preventing cascading timeouts during peak operational hours.",
        },
        {
          title: "The Road Ahead",
          content:
            "Transitioning the monolithic Go service into domain-driven microservices (e.g., separating patient ingest from historical read models) using CQRS patterns to further isolate fault domains.",
        },
      ],
    },
  },
  {
    id: "aegis-mesh",
    title: "AEGIS MESH:",
    subTitle: "Global Edge Architecture.",
    category: "INFRASTRUCTURE & DISTRIBUTED SYSTEMS",
    tags: ["Rust", "CDN", "Edge"],
    engineeringStack: {
      subtitle:
        "Core technologies selected for performance, safety, and reliability.",
      groups: [
        {
          label: "THE ENGINE",
          items: ["Rust", "Go", "Tokio", "gRPC", "WebAssembly"],
        },
        {
          label: "DATA & STORAGE",
          items: ["Redis", "PostgreSQL", "ScyllaDB", "S3", "RocksDB"],
        },
        {
          label: "INFRA & OPS",
          items: ["Kubernetes", "Terraform", "Istio", "Prometheus", "Datadog"],
        },
        {
          label: "NETWORK",
          items: ["eBPF", "Envoy", "QUIC", "TLS 1.3", "Anycast"],
        },
        {
          label: "TESTING",
          items: ["K6", "Jepsen", "Chaos Mesh", "Unit Testing"],
        },
        {
          label: "CI/CD",
          items: ["GitHub Actions", "ArgoCD", "Helm", "Kaniko"],
        },
      ],
    },
    fullDescription:
      "Replacing legacy CDN infrastructure with a custom-built, Rust-powered edge-caching layer that reduced cold-start latency by 64% for 12M global users.",
    links: [
      { label: "View Repository", url: "#" },
      { label: "Technical Docs", url: "#" },
    ],
    stats: [
      { label: "TIMELINE", value: "Q3 2023 - Q1 2024" },
      { label: "SCALE", value: "1.2M Req/sec Peak" },
      { label: "COST SAVINGS", value: "$220k / Month" },
    ],
    detailedSections: [
      {
        id: "executive-summary",
        title: "EXECUTIVE SUMMARY",
        content:
          "The mission was to eliminate vendor lock-in and provide sub-50ms global content delivery through a proprietary mesh network.\n\nAs lead system architect, I directed the migration from a third-party managed CDN to a custom-orchestrated edge mesh. The primary challenge was maintaining strong consistency for dynamic assets across 42 global POPs while minimizing the overhead of the data plane.",
        keyContribution:
          '"Designed a novel eventual-consistency protocol for edge metadata synchronization that reduced inter-region chatter by 40%, directly translating to lower cloud egress costs."',
      },
      {
        id: "system-architecture",
        title: "SYSTEM ARCHITECTURE",
        content:
          "Detailed architecture design and implementation of the edge nodes and control plane.",
        keyContribution: null,
      },
      {
        id: "engineering-stack",
        title: "ENGINEERING STACK",
        content:
          "Overview of technologies used including Rust, distributed key-value stores, and anycast routing.",
        keyContribution: null,
      },
      {
        id: "technical-decisions",
        title: "TECHNICAL DECISIONS",
        content: "Key decisions made during the design phase.",
        keyContribution: null,
      },
      {
        id: "measurable-impact",
        title: "MEASURABLE IMPACT",
        content: "Details on performance and impact.",
        keyContribution: null,
      },
      {
        id: "postmortem",
        title: "POSTMORTEM",
        content:
          "Lessons learned from the deployment and what we would do differently.",
        keyContribution: null,
      },
    ],
    problem: {
      title: "THE PROBLEM",
      description: "High costs and vendor lock-in with existing managed CDN.",
    },
    engineering: {
      title: "THE ENGINEERING",
      description: "Custom Rust-powered edge-caching layer.",
    },
    impact: {
      value: "64%",
      description: "latency reduction",
    },
    architecture: {
      title: "System Architecture",
      controlPlane: {
        label: "// Control Plane",
        items: ["Orchestrator", "Routing"],
      },
      dataPlane: {
        label: "// Data Plane",
        nodes: ["Edge Nodes", "Cache"],
      },
    },
    technicalDecisions: [
      {
        title: "Core Runtime Language",
        options: [
          { label: "Go (Standard)", isChosen: false },
          { label: "Rust (Aegis-Core)", isChosen: true },
        ],
        rationale:
          "We required zero-garbage-collection to maintain consistent P99 latency. Rust's memory safety and performance at the network level were non-negotiable for the Edge nodes.",
      },
      {
        title: "Global State Store",
        options: [
          { label: "Etcd", isChosen: false },
          { label: "ScyllaDB", isChosen: true },
        ],
        rationale:
          "For metadata propagation across 40+ regions, ScyllaDB provided superior throughput and lower cross-region replication lag compared to the consensus-heavy nature of Etcd.",
      },
      {
        title: "Inter-service Communication",
        options: [
          { label: "JSON / REST", isChosen: false },
          { label: "Protobuf / gRPC", isChosen: true },
        ],
        rationale:
          "Internal bandwidth costs and parsing overhead necessitated a binary protocol. gRPC reduced our payload sizes by 45% and enabled streaming telemetry.",
      },
    ],
    measurableImpact: {
      subtitle:
        "Hard data reflecting the project's success and operational efficiency.",
      items: [
        {
          label: "P99 LATENCY",
          value: "42",
          subValue: "ms",
          trend: "⚡ 64% improvement",
        },
        {
          label: "INFRASTRUCTURE COST",
          value: "-2.4",
          subValue: "M/yr",
          trend: "⚡ 35% improvement",
        },
        {
          label: "CACHE HIT RATIO",
          value: "94.8",
          subValue: "%",
          trend: "⚡ 12% improvement",
        },
        { label: "SYSTEM UPTIME", value: "99.999", subValue: "%", trend: "" },
      ],
    },
    postmortem: {
      subtitle: "A reflection on the challenges faced and future iterations.",
      items: [
        {
          title: "What went well?",
          content:
            'The decision to use Rust for the data plane was vindicated early. We saw zero segfaults during the initial rollout and the CPU overhead was significantly lower than anticipated, allowing us to downsize our edge instances. The phased "shadow-traffic" deployment strategy also meant zero downtime for existing users during the switchover.',
        },
        {
          title: "What would I change?",
          content:
            "We initially built our own metrics aggregation before realizing the volume of edge telemetry would overwhelm the pipeline. Switching to a managed Datadog integration earlier would have saved three weeks of internal engineering.",
        },
        {
          title: "The Road Ahead",
          content:
            "The next phase involves implementing WebAssembly plugins at the edge to allow tenants to run their own custom routing logic without compromising the secure sandbox of the data plane.",
        },
      ],
    },
  },
];
