import type { ProjectItem } from "$generated/types/Configuration";

export const projects: ProjectItem[] = [
  {
    id: "knik",
    title: "Knik",
    subTitle: "Local-First Inference.",
    category: "AI & REAL-TIME COMMUNICATIONS",
    fullDescription:
      "High latency and privacy concerns plague cloud-based voice assistants. The objective of Knik was to develop a local-first voice console utilizing the cutting-edge Kokoro-82M TTS model to achieve sub-second response times without sending private audio to the cloud.",
    links: null,
    stats: [{ label: "TIMELINE", value: "2024 - Till Date" }],
    detailedSections: [
      {
        id: "executive-summary",
        title: "EXECUTIVE SUMMARY",
        content:
          "High latency and privacy concerns plague cloud-based voice assistants. The objective of Knik was to develop a local-first voice console utilizing the cutting-edge Kokoro-82M TTS model to achieve sub-second response times without sending private audio to the cloud.",
        keyContribution:
          '"Architected a continuous audio streaming pipeline over WebSockets, decoupling the STT and TTS engines to allow mid-sentence interruption and playback synchronization."',
      },
      {
        id: "system-architecture",
        title: "SYSTEM ARCHITECTURE",
        content:
          "Detailed breakdown of the local model inference and WebSocket routing.",
        keyContribution: null,
      },
      {
        id: "engineering-stack",
        title: "ENGINEERING STACK",
        content: "Core technologies enabling local AI execution.",
        keyContribution: null,
      },
      {
        id: "technical-decisions",
        title: "TECHNICAL DECISIONS",
        content: "Key architectural decisions for real-time processing.",
        keyContribution: null,
      },
      {
        id: "measurable-impact",
        title: "MEASURABLE IMPACT",
        content: "Latency benchmarks and resource utilization metrics.",
        keyContribution: null,
      },
      {
        id: "postmortem",
        title: "POSTMORTEM",
        content: "Hardware limitations and future optimization paths.",
        keyContribution: null,
      },
    ],
    tags: ["AI", "Local First", "React", "FastAPI"],
    problem: {
      title: "THE PROBLEM",
      description:
        "High latency and privacy concerns with cloud-based voice assistants.",
    },
    engineering: {
      title: "THE ENGINEERING",
      description:
        "Integrated Kokoro-82M TTS with an async FastAPI backend and React frontend for sub-second latency and smooth UI.",
    },
    impact: {
      value: "Real-time",
      description: "local voice interaction",
    },
    architecture: {
      title: "System Architecture",
      controlPlane: {
        label: "// Control Plane",
        items: ["FastAPI Orchestrator", "MCP Router"],
      },
      dataPlane: {
        label: "// Data Plane",
        nodes: ["Kokoro TTS", "Local Tools"],
      },
      layers: [
        {
          label: "CONTROL PLANE / ORCHESTRATION",
          nodes: [
            {
              icon: "server",
              label: "FastAPI Orchestrator",
              description: "Async Python backend managing conversational state",
            },
            {
              icon: "router",
              label: "MCP Router",
              description: "Intelligent routing system for tool execution",
            },
          ],
        },
        {
          label: "DATA PLANE / INFERENCE",
          nodes: [
            {
              icon: "cpu",
              label: "Kokoro TTS",
              description: "Local 82M parameter text-to-speech engine",
            },
            {
              icon: "tool",
              label: "Local Tools",
              description: "Native integrations and tools payload",
            },
          ],
        },
      ],
    },
    technicalDecisions: [
      {
        title: "Communication Protocol",
        options: [
          { label: "REST Polling", isChosen: false },
          { label: "WebSockets", isChosen: true },
        ],
        rationale:
          "Real-time conversational AI requires full-duplex communication. WebSockets allowed us to stream audio chunks continuously as they were generated by the model, reducing perceived latency by over 800ms.",
      },
    ],
    engineeringStack: {
      subtitle: "Locally-hosted AI processing and reactive UI.",
      groups: [
        {
          label: "FRONTEND",
          items: ["React", "TypeScript", "Vite", "TailwindCSS"],
        },
        {
          label: "BACKEND",
          items: ["Python", "FastAPI", "Uvicorn", "WebSockets"],
        },
        {
          label: "AI ENGINE",
          items: ["Kokoro-82M", "ONNXRuntime", "PyAudio", "Whisper"],
        },
      ],
    },
    measurableImpact: {
      subtitle: "Performance metrics for the local AI pipeline.",
      items: [
        {
          label: "TTS LATENCY",
          value: "350",
          subValue: "ms",
          trend: "⚡ 3x faster than cloud APIs",
        },
        {
          label: "MEMORY FOOTPRINT",
          value: "1.2",
          subValue: "GB",
          trend: "⚡ Edge deployment ready",
        },
      ],
    },
    postmortem: {
      subtitle: "Reflections on building local AI.",
      items: [
        {
          title: "What went well?",
          content:
            "The Kokoro model's parameter efficiency allowed for incredibly fast CPU inference. Decoupling the audio buffering from the inference thread completely eliminated UI stuttering during playback.",
        },
        {
          title: "The Road Ahead",
          content:
            "Migrating the inference engine to WebAssembly (WASM) or WebGPU to run entirely in the browser. This will completely eliminate the need for a local Python backend and drastically simplify installation for end-users.",
        },
      ],
    },
  },
  {
    id: "lilac",
    title: "Lilac",
    subTitle: "Zero-Dependency Logging.",
    category: "DEVELOPER TOOLS & OPEN SOURCE",
    fullDescription:
      "Lilac was born out of frustration with existing logging libraries that were bloated with dependencies. The goal was to build a zero-dependency, strongly-typed logger that supports custom transports and structured JSON logging out of the box.",
    links: null,
    stats: [{ label: "TIMELINE", value: "2024 - Till Date" }],
    detailedSections: [
      {
        id: "executive-summary",
        title: "EXECUTIVE SUMMARY",
        content:
          "Lilac was born out of frustration with existing logging libraries that were bloated with dependencies. The goal was to build a zero-dependency, strongly-typed logger that supports custom transports and structured JSON logging out of the box.",
        keyContribution:
          '"Implemented a lazy-evaluation mechanism for log arguments, ensuring complex object stringification only occurs if the log level is active, saving considerable CPU cycles in production."',
      },
      {
        id: "system-architecture",
        title: "SYSTEM ARCHITECTURE",
        content: "Architecture of the logger core and transport plugins.",
        keyContribution: null,
      },
      {
        id: "engineering-stack",
        title: "ENGINEERING STACK",
        content: "NPM package tooling and TypeScript build chain.",
        keyContribution: null,
      },
      {
        id: "technical-decisions",
        title: "TECHNICAL DECISIONS",
        content: "Decisions regarding bundle size and API surface.",
        keyContribution: null,
      },
      {
        id: "measurable-impact",
        title: "MEASURABLE IMPACT",
        content: "Bundle size reductions and NPM download stats.",
        keyContribution: null,
      },
      {
        id: "postmortem",
        title: "POSTMORTEM",
        content: "Learnings from publishing to the NPM registry.",
        keyContribution: null,
      },
    ],
    tags: ["TypeScript", "NPM"],
    problem: {
      title: "THE PROBLEM",
      description:
        "Debugging was slow and inefficient due to lack of structured logging.",
    },
    engineering: {
      title: "THE ENGINEERING",
      description:
        "Conceptualized and deployed a lightweight TypeScript logging package to NPM.",
    },
    impact: {
      value: "20%",
      description: "reduction in debugging time",
    },
    architecture: {
      title: "System Architecture",
      controlPlane: {
        label: "// Core",
        items: ["Lightweight Logger", "Custom Transports"],
      },
      dataPlane: {
        label: "// Output",
        nodes: ["Console", "File", "Remote"],
      },
      layers: [
        {
          label: "CORE SYSTEM",
          nodes: [
            {
              icon: "core",
              label: "Lightweight Logger",
              description: "Zero-dependency TypeScript logging core",
            },
            {
              icon: "plugin",
              label: "Custom Transports",
              description: "Pluggable sink interface for log routing",
            },
          ],
        },
        {
          label: "OUTPUT SINKS",
          nodes: [
            {
              icon: "terminal",
              label: "Console",
              description: "Standard out/err with rich formatting",
            },
            {
              icon: "file",
              label: "File",
              description: "Local file system logging transport",
            },
            {
              icon: "network",
              label: "Remote",
              description: "Network transports for observability",
            },
          ],
        },
      ],
    },
    technicalDecisions: [
      {
        title: "Dependency Management",
        options: [
          { label: "Third-party formatters", isChosen: false },
          { label: "Zero-dependency core", isChosen: true },
        ],
        rationale:
          "Supply chain security is paramount for a logging library that runs in every service. By writing our own lightweight JSON stringifier and formatters, we eliminated risk of malicious downstream updates and kept the bundle size under 4KB.",
      },
    ],
    engineeringStack: {
      subtitle: "Zero-dependency utility package optimized for NPM.",
      groups: [
        { label: "LANGUAGE", items: ["TypeScript", "Node.js"] },
        {
          label: "BUILD & TOOLING",
          items: ["TSup", "ESLint", "Prettier", "Jest"],
        },
        { label: "CI/CD", items: ["GitHub Actions", "NPM Registry"] },
      ],
    },
    measurableImpact: {
      subtitle: "Metrics tracking package efficiency and adoption.",
      items: [
        {
          label: "UNPACKED SIZE",
          value: "114",
          subValue: "kB",
          trend: "⚡ Supports Kafka, Push, etc.",
        },
        {
          label: "DEBUGGING TIME",
          value: "20",
          subValue: "%",
          trend: "⚡ Reduced via strict typings",
        },
      ],
    },
    postmortem: {
      subtitle: "Learnings from maintaining open-source tooling.",
      items: [
        {
          title: "What went well?",
          content:
            "The strict TypeScript generic bindings for log metadata allowed developers to catch schema errors at compile-time rather than runtime, which became the most praised feature of the library.",
        },
        {
          title: "The Road Ahead",
          content:
            "Adding native OpenTelemetry integration as a default transport to automatically trace logs across microservice boundaries without additional configuration.",
        },
      ],
    },
  },
  {
    id: "vernix",
    title: "Vernix",
    subTitle: "Accessible UI Primitives.",
    category: "DESIGN SYSTEMS & FRONTEND ARCHITECTURE",
    fullDescription:
      "Inconsistent design patterns and slow UI development fragmented our engineering efforts across multiple frontends. Vernix was developed as a unified Svelte component library to enforce design system consistency and provide pre-built accessible components with smooth transitions.",
    links: null,
    stats: [{ label: "TIMELINE", value: "2024 - Till Date" }],
    detailedSections: [
      {
        id: "executive-summary",
        title: "EXECUTIVE SUMMARY",
        content:
          "Inconsistent design patterns and slow UI development fragmented our engineering efforts across multiple frontends. Vernix was developed as a unified Svelte component library to enforce design system consistency and provide pre-built accessible components with smooth transitions.",
        keyContribution:
          '"Built a headless, unstyled core alongside a styled thematic layer using CSS variables, allowing consumer apps to inherit logic while retaining deep branding control."',
      },
      {
        id: "system-architecture",
        title: "SYSTEM ARCHITECTURE",
        content: "Component composition and theming architecture.",
        keyContribution: null,
      },
      {
        id: "engineering-stack",
        title: "ENGINEERING STACK",
        content: "Component framework and bundling tooling.",
        keyContribution: null,
      },
      {
        id: "technical-decisions",
        title: "TECHNICAL DECISIONS",
        content: "Styling approach and accessibility considerations.",
        keyContribution: null,
      },
      {
        id: "measurable-impact",
        title: "MEASURABLE IMPACT",
        content: "Development speed improvements across teams.",
        keyContribution: null,
      },
      {
        id: "postmortem",
        title: "POSTMORTEM",
        content: "Svelte 5 adoption and package maintenance.",
        keyContribution: null,
      },
    ],
    tags: ["Svelte", "UI/UX", "NPM"],
    problem: {
      title: "THE PROBLEM",
      description:
        "Inconsistent design patterns and slow UI development across projects.",
    },
    engineering: {
      title: "THE ENGINEERING",
      description:
        "Developed and published a component library with 10+ reusable components and built-in transitions.",
    },
    impact: {
      value: "10+",
      description: "reusable components",
    },
    architecture: {
      title: "Library Structure",
      controlPlane: {
        label: "// Components",
        items: ["Buttons", "Inputs", "Modals"],
      },
      dataPlane: {
        label: "// Integration",
        nodes: ["SvelteKit", "Vite"],
      },
      layers: [
        {
          label: "UI COMPONENTS LAYER",
          nodes: [
            {
              icon: "button",
              label: "Components",
              description: "Buttons, Inputs, Modals & Base Primitives",
            },
            {
              icon: "theme",
              label: "Theming System",
              description: "CSS variables and theme injection",
            },
          ],
        },
        {
          label: "INTEGRATION LAYER",
          nodes: [
            {
              icon: "svelte",
              label: "SvelteKit",
              description: "Native framework integration & SSR",
            },
            {
              icon: "vite",
              label: "Vite",
              description: "Fast compilation & asset bundling",
            },
          ],
        },
      ],
    },
    technicalDecisions: [
      {
        title: "Styling Strategy",
        options: [
          { label: "Tailwind inside Components", isChosen: false },
          { label: "CSS Variables (CSS-in-JS)", isChosen: true },
        ],
        rationale:
          "Baking utility classes into the distributed package forced consumer apps to match our exact Tailwind config. By defining semantic CSS variables instead, consumers can hot-swap themes globally with a single class change on the body element.",
      },
    ],
    engineeringStack: {
      subtitle: "Modern frontend tooling for component libraries.",
      groups: [
        { label: "FRAMEWORK", items: ["Svelte 4", "SvelteKit", "TypeScript"] },
        { label: "STYLING", items: ["SCSS", "CSS Variables", "PostCSS"] },
        { label: "DOCUMENTATION", items: ["Storybook", "Histoire"] },
      ],
    },
    measurableImpact: {
      subtitle: "Impact of systemic component reuse.",
      items: [
        {
          label: "UI DEV SPEED",
          value: "3x",
          subValue: "",
          trend: "⚡ Faster feature delivery",
        },
        {
          label: "COMPONENTS",
          value: "45",
          subValue: "+",
          trend: "⚡ Fully accessible",
        },
      ],
    },
    postmortem: {
      subtitle: "Reflections on design system maintainability.",
      items: [
        {
          title: "What went well?",
          content:
            "Extracting complex accessibility logic (like focus-trapping in modals and keyboard navigation in dropdowns) into the library meant consumer applications became instantly compliant with ARIA standards without extra developer effort.",
        },
        {
          title: "The Road Ahead",
          content:
            "Migrating the entire codebase from Svelte 4 to Svelte 5 to take advantage of runes and the new reactivity paradigm, which will further reduce bundle size and simplify internal component state.",
        },
      ],
    },
  },
  {
    id: "hospital-api",
    title: "Hospital API",
    subTitle: "Patient Lookup Optimization.",
    category: "BACKEND & DATA OPTIMIZATION",
    fullDescription:
      "The Hospital API faced critical performance bottlenecks, where slow retrieval of patient data was actively affecting care coordination efficiency in urgent scenarios. I spearheaded the optimization of the backend service, introducing advanced filtering mechanisms and database query optimization.",
    links: null,
    stats: [{ label: "TIMELINE", value: "2021-22" }],
    detailedSections: [
      {
        id: "executive-summary",
        title: "EXECUTIVE SUMMARY",
        content:
          "The Hospital API faced critical performance bottlenecks, where slow retrieval of patient data was actively affecting care coordination efficiency in urgent scenarios. I spearheaded the optimization of the backend service, introducing advanced filtering mechanisms and database query optimization.",
        keyContribution:
          '"Implemented a compound indexing strategy combined with Redis-based query caching that brought P99 response times for complex patient history lookups down from 3 seconds to under 200ms."',
      },
      {
        id: "system-architecture",
        title: "SYSTEM ARCHITECTURE",
        content: "Data flow and caching hierarchy.",
        keyContribution: null,
      },
      {
        id: "engineering-stack",
        title: "ENGINEERING STACK",
        content: "Backend languages, databases, and infrastructure.",
        keyContribution: null,
      },
      {
        id: "technical-decisions",
        title: "TECHNICAL DECISIONS",
        content: "Database choice and caching invalidation strategies.",
        keyContribution: null,
      },
      {
        id: "measurable-impact",
        title: "MEASURABLE IMPACT",
        content: "Query latency and system load reductions.",
        keyContribution: null,
      },
      {
        id: "postmortem",
        title: "POSTMORTEM",
        content: "Scaling challenges and future data migration plans.",
        keyContribution: null,
      },
    ],
    tags: ["Backend", "API", "Filtering"],
    problem: {
      title: "THE PROBLEM",
      description:
        "Slow retrieval of critical patient data affecting care coordination efficiency.",
    },
    engineering: {
      title: "THE ENGINEERING",
      description:
        "Implemented five advanced filtering mechanisms within the patient records API.",
    },
    impact: {
      value: "60%",
      description: "faster data retrieval",
    },
    architecture: {
      title: "API Architecture",
      controlPlane: {
        label: "// Logic",
        items: ["Advanced Formatting", "Query Optimization"],
      },
      dataPlane: {
        label: "// Data",
        nodes: ["Database", "Cache"],
      },
      layers: [
        {
          label: "LOGIC LAYER",
          nodes: [
            {
              icon: "logic",
              label: "Query Optimization",
              description: "Compound indexing & query generation",
            },
            {
              icon: "format",
              label: "Advanced Formatting",
              description: "Data transformation and hydration",
            },
          ],
        },
        {
          label: "DATA LAYER",
          nodes: [
            {
              icon: "database",
              label: "Database",
              description: "Main analytical patient records storage",
            },
            {
              icon: "cache",
              label: "Cache",
              description: "Redis-based query caching layer",
            },
          ],
        },
      ],
    },
    technicalDecisions: [
      {
        title: "Caching Strategy",
        options: [
          { label: "Time-based Expiration (TTL)", isChosen: false },
          { label: "Event-driven Invalidation", isChosen: true },
        ],
        rationale:
          "Patient health records are highly sensitive to staleness. Relying on TTL caching was deemed a clinical risk. We implemented a Postgres trigger system that emits an event to our Go service, actively invalidating the exact Redis keys affected by any write or update.",
      },
    ],
    engineeringStack: {
      subtitle: "High-reliability healthcare backend systems.",
      groups: [
        { label: "BACKEND", items: ["Go", "Gin", "gRPC", "GraphQL"] },
        { label: "DATABASE", items: ["PostgreSQL", "Redis", "Elasticsearch"] },
        { label: "INFRASTRUCTURE", items: ["AWS EKS", "Terraform", "Docker"] },
      ],
    },
    measurableImpact: {
      subtitle: "Impact on clinical data retrieval speed.",
      items: [
        {
          label: "QUERY LATENCY",
          value: "200",
          subValue: "ms",
          trend: "⚡ Down from 3000ms",
        },
        {
          label: "DATA RETRIEVAL",
          value: "60",
          subValue: "%",
          trend: "⚡ Faster overall lookup",
        },
      ],
    },
    postmortem: {
      subtitle: "Reflections on mission-critical medical systems.",
      items: [
        {
          title: "What went well?",
          content:
            "Offloading the full-text search requirements from Postgres `LIKE` queries to a dedicated Elasticsearch cluster immediately stabilized our primary database CPU utilization, preventing cascading timeouts during peak operational hours.",
        },
        {
          title: "The Road Ahead",
          content:
            "Transitioning the monolithic Go service into domain-driven microservices (e.g., separating patient ingest from historical read models) using CQRS patterns to further isolate fault domains.",
        },
      ],
    },
  },
];
