info:
  version: 1.0.0
  title: Project Me
groupedTypes:
  APISchema:
    $ref: "./docs/types/APISchema.yaml#/APISchema"
  Projects:
    $ref: "./docs/types/Projects.yaml#/Projects"
  GitHub:
    $ref: "./docs/types/GitHub.yaml#/GitHub"
  Gmail:
    $ref: "./docs/types/Gmail.yaml#/Gmail"
  Client:
    $ref: "./docs/types/Client.yaml#/Client"
  Spotify:
    $ref: "./docs/types/Spotify.yaml#/Spotify"
